### ISSUE TITLE
Add support for multiple configuration files

### ISSUE THREAD

**Issue by ShaunParsons** [nordcloud/serverless-plugin-additional-stacks#30]
Serverless supports loading from multiple configuration files: https://www.serverless.com/framework/docs/providers/aws/guide/variables#multiple-configuration-files

Example:
```yml
resources:
  - Resources:
      ApiGatewayRestApi:
        Type: AWS::ApiGateway::RestApi

  - ${file(resources/first-cf-resources.yml)}
  - ${file(resources/second-cf-resources.yml)}

  - Outputs:
      CognitoUserPoolId:
      Value:
        Ref: CognitoUserPool
```

However, this does not work with additional stacks. The following config will cause `stack` to be an array [here](https://github.com/nordcloud/serverless-plugin-additional-stacks/blob/master/index.js#L226).
```yml
additionalStacks:
  permanent:
    - ${file(./serverless/custom/database.yml)}
    - ${file(./serverless/custom/network.yml)}
```
