### ISSUE TITLE
Error when deploying - TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by TroyCoombs** [nordcloud/serverless-plugin-additional-stacks#37]
Getting this error when the additional stack is being deployed, either 
sls deploy or sls deploy additionalstacks --stage staging

Wondering what I'm missing?

Serverless.yml portion:
```
custom:
  adfLeadsTopicName: ${self:provider.stage}-${self:service.name}
  additionalStacks:
    stackName:
      Deploy: Before
      DeployParameters: []
      StackName: ${self:provider.stage}-${self:service.name}-resources
      Description: 'Creates base resources needed for ADF Leads. Stack creates resources, does not have permission to delete them. The adf-leads stack depends on this.'
      Resources:
        ### Create SNS Topic
        AdfLeadsTopic:
          Type: AWS::SNS::Topic
          Properties:
            TopicName: ${self:custom.adfLeadsTopicName}
            DisplayName: ${self:custom.adfLeadsTopicName}
```

Error is:
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: mailparser@^3.0.1
Serverless: Packaging service...
 
  Type Error ---------------------------------------------
 
  TypeError: Object.fromEntries is not a function
      at AdditionalStacksPlugin.mergeAdditionalStacks (/Users/***/serverless/aws/prospect-leads/adf/node_modules/serverless-plugin-additional-stacks/index.js:103:19)
      at AdditionalStacksPlugin.getAdditionalStacks (/Users/***/serverless/aws/prospect-leads/adf/node_modules/serverless-plugin-additional-stacks/index.js:122:103)
      at AdditionalStacksPlugin.getAdditionalBeforeStacks (/Users/***/serverless/aws/prospect-leads/adf/node_modules/serverless-plugin-additional-stacks/index.js:127:25)
      at AdditionalStacksPlugin.beforeDeployGlobal (/Users/***/serverless/aws/prospect-leads/adf/node_modules/serverless-plugin-additional-stacks/index.js:152:25)
      at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55)
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)

**Comment by kennu** [comment]
Hi @TroyCoombs, might be an issue with older Node.js? Object.fromEntries is supported in Node.js 12.x and later.

**Comment by TroyCoombs** [comment]
@kennu  I'm running 12.x as seen below.  Can't figure out what the problem, feels like it something silly I'm missing.

```
# Provider
provider:
  name: aws
  runtime: nodejs12.x
```
